add_library(libSceAudioIn SHARED EXCLUDE_FROM_ALL Export.cpp)
target_include_directories(libSceAudioIn PRIVATE ${LIBS_INCLUDE_DIR} ${CMAKE_SOURCE_DIR}/3rdparty/SDL2/include)
target_link_libraries(libSceAudioIn PRIVATE SDL2-static)
if(NOT APPLE)
    target_link_options(libSceAudioIn PRIVATE LINKER:--exclude-libs,ALL)
endif()
configure_windows_unwind(libSceAudioIn)

if(BUILD_TESTING)
    add_test_executable(guest_audio_in_tests ${LIBS_INCLUDE_DIR}/tests/GuestAudioIn.cpp)
    target_include_directories(guest_audio_in_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_audio_in_tests PRIVATE libSceAudioIn libc)
    configure_windows_unwind(guest_audio_in_tests)
    add_test(NAME guest_audio_in_capture COMMAND guest_audio_in_tests capture)
    add_test(NAME guest_audio_in_no_device COMMAND guest_audio_in_tests none)
    if(WIN32)
        set_tests_properties(guest_audio_in_capture guest_audio_in_no_device PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libSceAudioIn>")
    endif()
endif()
