add_library(libScePosixForWebKit SHARED EXCLUDE_FROM_ALL Export.cpp Resolver.cpp Filesystem.cpp)
target_include_directories(libScePosixForWebKit PRIVATE ${LIBS_INCLUDE_DIR})
target_link_libraries(libScePosixForWebKit PRIVATE libSceNet)
if(WIN32)
    target_link_libraries(libScePosixForWebKit PRIVATE ws2_32)
endif()
configure_windows_unwind(libScePosixForWebKit)

if(BUILD_TESTING)
    add_test_executable(guest_posix_filesystem_tests ${LIBS_INCLUDE_DIR}/tests/GuestPosixFilesystem.cpp)
    target_include_directories(guest_posix_filesystem_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_posix_filesystem_tests PRIVATE libScePosixForWebKit libkernel libc)
    configure_windows_unwind(guest_posix_filesystem_tests)
    add_test(NAME guest_posix_filesystem COMMAND guest_posix_filesystem_tests)
    set_tests_properties(guest_posix_filesystem PROPERTIES TIMEOUT 30)
    if(WIN32)
        set_tests_properties(guest_posix_filesystem PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libScePosixForWebKit>")
    endif()
    add_test_executable(guest_resolver_tests ${LIBS_INCLUDE_DIR}/tests/GuestResolver.cpp)
    target_include_directories(guest_resolver_tests PRIVATE ${LIBS_INCLUDE_DIR})
    target_link_libraries(guest_resolver_tests PRIVATE libScePosixForWebKit libSceNet libc)
    configure_windows_unwind(guest_resolver_tests)
    add_test(NAME guest_resolver COMMAND guest_resolver_tests)
    if(WIN32)
        target_link_libraries(guest_resolver_tests PRIVATE ws2_32)
        set_tests_properties(guest_resolver PROPERTIES ENVIRONMENT_MODIFICATION
            "PATH=path_list_prepend:$<TARGET_FILE_DIR:libScePosixForWebKit>")
    endif()
endif()
